FROM golang:1.17.5-alpine3.14

ENV DATABASE_URL="postgres://username:password@localhost:5432/database_name"

RUN mkdir /home/backend/v2
ADD . /home/backend/v2
WORKDIR /home/backend/v2
## Add this go mod download command to pull in any dependencies
RUN go mod download
## Our project will now successfully build with the necessary go libraries included.
RUN go build -o server .
## Our start command which kicks off
## our newly created binary executable
RUN chmod +x /app/main
CMD ["/app/main"]