version: "3.7"
services:
  pubsub-api-backend:
    image: pubsub-api/backend
    build: 
      context: ./backend/v1
      dockerfile: Dockerfile.dev
    container_name: pubsub-api-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/home/backend/app
    env_file:
      - .env
  # pubsub-api-frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"
  #   container_name: pubsub-api-frontend
  #   stdin_open: true 
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/home/frontend
  #     - /home/frontend/node_modules
  #   depends_on: 
  #   - pubsub-api-backend
  #   links: 
  #   - pubsub-api-backend
    
    
  