version: "3.3"
services:
  backend:
    image: zenith110/pubsub-backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 8080:8080
    container_name: backend
  discord-bot:
    image: zenith110/pubsub-bot
  pubsub-api-grapqhl:
    image: zenith110/pubsub-backend-grapqhl
    container_name: grapqhl
    ports:
      - "8443:8443"
    env_file:
      - .env
  prometheus:
  image: prom/prometheus:latest
  container_name: prometheus
  restart: unless-stopped
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
  command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
  ports:
    - 9090:9090
  traefik:
    image: traefik/whoami
    ports:
      - "9080:8080"
    container_name: "traefik"
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
  tempo:
    image: bitnami/grafana-tempo
    container_name: tempo
    volumes:
      - ./tempo.yaml:/bitnami/grafana-tempo/conf/tempo.yaml

volumes:
  prometheus_data:
