version: "3"
services:
  pubsub-api-backend-v1:
    image: pubsub-api/backend
    build:
      context: ./backend/python
      dockerfile: dev.dockerfile
    container_name: pubsub-api-backend-v1
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    volumes:
      - ./backend/python/src:/home/backend/app
    ports:
      - "8080:8080"
    env_file:
      - .env
  pubsub-api-backend-v2:
    image: pubsub-api/backend-v2
    build:
      context: ./backend/go/src
      dockerfile: dev.dockerfile
    container_name: pubsub-api-backend-v2
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env
  pubsub-api-frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: pubsub-api-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - pubsub-api-backend-v1
      - pubsub-api-backend-v2
    links:
      - pubsub-api-backend-v1
      - pubsub-api-backend-v2
  promethus:
    image: prom/prometheus
    ports:
      - "5000:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
