version: "3.7"
services:
  pubsub-api-backend:
    image: pubsub-api/backend
    build: 
      context: ./backend/v1
      dockerfile: Dockerfile.dev
    container_name: pubsub-api-backend
    restart: unless-stopped
    ports:
      - 5000:5000
  pubsub-api-frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true 
    ports:
      - 3000:3000
    depends_on: 
    - pubsub-api-backend
    links: 
    - pubsub-api-backend
    
    
  