version: "3"
services:
  pubsub-api-backend:
    image: pubsub-api/backend
    build:
      context: ./backend/python
      dockerfile: Dockerfile.dev
    container_name: pubsub-api-backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    volumes:
      - ./backend/python/src:/home/backend/app
    ports:
      - "8080:8080"
    env_file:
      - .env
  pubsub-api-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: pubsub-api-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - pubsub-api-backend
    links:
      - pubsub-api-backend
