version: "3.3"
services:
  backend:
    image: zenith110/pubsub-python-backend-qa
    ports:
      - 8080:8080
    container_name: backend
  discord-bot:
    image: zenith110/pubsub-bot-qa
    container_name: bot
  pubsub-api-grapqhl:
    image: zenith110/pubsub-graphql-qa
    container_name: grapqhl
    ports:
      - "8443:8443"
    env_file:
      - .env
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
  traefik:
    image: traefik/whoami
    ports:
      - "7080:8080"
    container_name: "traefik"
  loki:
    image: grafana/loki
    container_name: loki
    command: "-config.file=/etc/loki/config/loki-config.yml"
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config/loki-config.yml
      - ./loki-data:/etc/loki
      - ./loki-data/data:/data/loki
      - ./loki-data/index:/opt/loki/index
      - ./loki-data/chunks:/opt/loki/chunks
    restart: "unless-stopped"
  tempo:
    image: grafana/tempo
    container_name: tempo
  promtail:
    image: grafana/promtail
    container_name: promtail
    user: root
    volumes:
      - ./promtail_storage/logs:/var/logs
      - ./promtail-config.yml:/etc/promtail/config/promtail-config.yml
      - ./var/log:/var/log
    ports:
      - "9080:9080"
    restart: "unless-stopped"
    command: "-config.file=/etc/promtail/config/promtail-config.yml"
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    # ports:
    #   - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped

volumes:
  prometheus_data:
