// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pubsub struct {
	Name     string `json:"name"`
	Image    string `json:"image"`
	Saledate string `json:"saledate"`
	Onsale   bool   `json:"onsale"`
}

type PubsubQuery struct {
	Name *string `json:"name"`
}

type Pubsubs struct {
	Pubsubs []*Pubsub `json:"pubsubs"`
}
