# set base image (host OS)
FROM python:3.7.9-slim


# set the working directory in the container
WORKDIR /backend/

# copy the content of the local src directory to the working directory
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN black .
COPY src/ .
CMD [ "python", "./app.py" ]

