# Deploys a payload to the server to get the latest data
name: Merge QA
# Deploys data based off master branch
on:
  pull_request:
    types: [closed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Cleaning_up_Terraform:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: terraform_cleanup
        run: |
          terraform destroy
